alias .f='dotfiles'
alias b="bin/console"
alias cont="killall -CONT"
alias console="tjmOpenApp=1 o console"
alias cp="cp -pri"
alias du="du -h"
alias d1="d -d 1"
alias df="df -h"
alias ff="tjmOpenApp=1 o ff"
alias ffd="tjmOpenApp=1 o ffd"
alias g='git'
alias gdiff="git diff --no-index"
alias gdiffw="gdiff -w"
alias l="ls -F --color"
alias l1="l -1h"
alias l1a="l1 -A"
alias l1r="l1 -R"
alias la="l -A"
alias ll="l -lh"
alias lr="l -R"
alias lla="ll -A"
alias lld="ll -d"
alias llr="ll -R"
alias mv="mv -i"
alias og="tjmOpenApp=1 o git"
alias ogit="tjmOpenApp=1 o git"
alias ot="tjmOpenApp=1 o t"
alias rmi=" rm -i"
alias scp="scp -pr"
alias ssha="ssh -A"
alias stop="killall -STOP"
alias svnstatus="svn status --ignore-externals"
alias svnstatusa="svn status"
alias svnupdate="svn update --ignore-externals"
alias svnupdatea="svnupdate"
alias tcpu="top -S -ocpu -s 2"
alias tmem='top -S -orsize -s 5'
alias tt="top -S -n 0 -s 5"
alias ttime='top -otime -s 5'
alias x="exit"

