if test -z "${TJM_DOTFILES_PATH}"; then
	TJM_DOTFILES_PATH=$(dirname $(dirname $(readlink -f "${BASH_SOURCE[0]}")))
	export TJM_DOTFILES_PATH
fi
#--load all conf
if [ -z "$TJM_ENVLOADED" ]; then
	. "${TJM_DOTFILES_PATH}/sh/env.sh"
fi
. "${TJM_DOTFILES_PATH}/sh/load.sh"
