set go-=T		" hide toolbar
set bg=dark
if &background == "dark"
	hi normal guibg=black guifg=white
	set transp=8
endif

"=====
"==styles
"=====

"--font
set guifont=Menlo\ Regular:h16

"--repeat colors from vimrc that get overridden by macvim
colorscheme koehler
highlight NonText ctermfg=darkGray guifg=gray43
highlight SpecialKey ctermfg=darkGray guifg=gray43
highlight GitGutterAdd ctermfg=green guifg=green
highlight GitGutterChange ctermfg=yellow guifg=yellow
highlight GitGutterDelete ctermfg=red guifg=red
