set go-=T		" hide toolbar
set bg=dark
" if &background == "dark"
	" hi normal guibg=black guifg=white
	" if has('gui_macvim')
		" set transp=8
	" endif
" endif

"--default window size
set columns=100
set lines=35

"=====
"==styles
"=====

source ~/.vim/colors.vim

"--font
set guifont=Menlo\ Regular\ 14,Liberation\ Mono\ 14,Menlo\ Regular:h14,Inconsolata:h14
