set go-=T		" hide toolbar
set bg=dark
" if &background == "dark"
	" hi normal guibg=black guifg=white
	" if has('gui_macvim')
		" set transp=8
	" endif
" endif

"=====
"==styles
"=====

source ~/.vim/colors.vim

"--font
set guifont=Menlo\ Regular:h16
