%if "#{>=,e|#{$TJMTCOLORS},256}"
	set -g @c0 "colour120"
	set -g @c0Alt "colour232"
	set -g @c0Dim "colour36"
	set -g @c0DimAlt "colour234"
	set -g @c1Alt "black"
	set -g @c1 "green"
	set -g @c1Emph "colour47"
	set -g @c2Alt "brightgreen"
	set -g @c2 "black"
	set -g @c3Alt "colour238"
	set -g @c3 "colour42"
%else
	set -g @c0 "brightgreen"
	set -g @c0Alt "black"
	set -g @c0Dim "brightcyan"
	set -g @c0DimAlt "brightblack"
	set -g @c1Alt "black"
	set -g @c1 "green"
	set -g @c1Emph "brightgreen"
	set -g @c2Alt "green"
	set -g @c2 "black"
	set -g @c3Alt "brightblack"
	set -g @c3 "brightcyan"
%endif
