#==keys
#--prefix
set -g prefix C-f
bind C-f send-prefix
set -g prefix2 C-l
bind C-l send-prefix -2
#-! alt key?
# bind -n M-space send-prefix
#-vi keys in copy mode
set -g mode-keys vi

#==ui
source -F "#{d:current_file}/colors.conf"

#--status
set -g status-interval 60
set -g status-justify centre
set -g status-left " #[bold]S#S#{?client_prefix,>, }#[default] "
set -g status-left-style bold
set -g status-position top
set -g status-right "| #{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] | }BAT:#(os batterylevel) | %m/%d#[bold] %H:%M "
set -gF status-style "bg=##{?client_prefix,#{@c1Emph},#{@c1}},fg=#{@c1Alt}"
set -gF window-status-style "bg=#{@c2Alt},fg=#{@c2},bold"
set -g window-status-current-format " #I:#W#{?window_flags,#{window_flags},:} "
set -gF window-status-current-style "bg=#{@c1Emph},bold"
set -g window-status-format " #I:#W#{?window_flags,#{window_flags},:} "
set -g window-status-separator ""

#--windows
#-don't auto rename windows with last command so we can manually name them
set -g allow-rename off
#-start windows / panes at one for easier switching
set -g base-index 1
setw -g pane-base-index 1

#--panes
set -gF window-style "bg=#{@c0DimAlt},fg=#{@c0Dim}"
set -gF window-active-style "bg=#{@c0Alt},fg=#{@c0}"
set -g pane-border-status top
#-! #{pane_title}
set -g pane-border-format "#{pane_index}: #{=/-30/…:pane_current_path} >#{pane_current_command}#{?#{pane_mode}, #[bold][#{pane_mode}]#[default]}#{?#{mouse},#[align=right]#[range=control|8][#{?#{window_zoomed_flag},u,z}]#[norange]#[range=control|9][x]#[norange],}"
set -gF pane-border-style "bg=#{@c1},fg=#{@c1Alt}"
set -gF pane-border-style "bg=#{@c0DimAlt},fg=#{@c1Emph}"
set -gF pane-active-border-style "bg=#{@c1Emph},fg=#{@c1Alt}"
set -gF mode-style "noattr,bg=#{@c1Emph},fg=#{@c1Alt}"

#--message
set -gF message-command-style "bg=#{@c3Alt},fg=#{@c3},fill=#{@c3Alt}"
set -gF message-style "bg=#{@c1Alt},fg=#{@c1Emph},fill=#{@c1Alt}"

#--clock
set -gF clock-mode-color "#{@c1}"

#==keys
#--improve copy paste experience
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection
#-don't like auto-copy on drag end
unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDown1Pane send -X cancel \; select-pane -t =
#--panes
bind | split-window -h
bind - split-window -v

#==ux
set -g mouse on
#-message display time
set -g display-time 0
#-use OS clipboard
set -s set-clipboard on
