if test -z "${TJM_DOTFILES_PATH}"; then
	TJM_DOTFILES_PATH=$(dirname $(dirname $(readlink -f "${(%):-%x}")))
	export TJM_DOTFILES_PATH
fi
if [ -z "$TJM_ENVLOADED" ]; then
	. "${TJM_DOTFILES_PATH:-$HOME/.dotfiles}/sh/env.sh"
fi
if [[ -n "${VIMRUNTIME+x}" && -f "$TJM_DOTFILES_PATH/sh/load.sh" ]]; then
	setopt aliases
	source "$TJM_DOTFILES_PATH/sh/load.sh"
fi
