if test -z "${TJMDOT}"; then
	TJMDOT=$(dirname $(dirname $(readlink -f "${(%):-%x}")))
	export TJMDOT
fi
if [ -z "$TJMENVLOADED" ]; then
	#--helper: set env variable if not set
	setdefaultenv(){
		if [ -z "${(P)1}" ]; then
			senv "$@"
		fi
	}
	setdefaultvar(){
		if [ -z "${(P)1}" ]; then
			svar "$@"
		fi
	}
	#--load env
	. "${TJMDOT:-$HOME/.dotfiles}/sh/env.sh"
fi
#--ensure aliases are used properly for Vim's `!` command execuation
#-! loads other interactive stuff than aliases, probably not wanted for non-interactive call
if [[ -n "${VIMRUNTIME+x}" && ! -o interactive ]]; then
	setopt aliases
	source "$TJMDOT/sh/load.sh"
fi
