#==sh stuff
source "$TJMDOT/sh/load.sh"

#==autosuggest
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

#==plugins
source "$TJMDOT/zsh/plugins.zsh"

#==options
setopt AUTO_CD #-# automatically change directory

#===completions
unsetopt correctall #-# auto correction of commands
unsetopt LIST_BEEP #-# disable awful errors when autocompleting
#--case insenstive
#-@ via https://stackoverflow.com/a/69014927
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
autoload -Uz compinit && compinit
#---git completions seem to be broken for files, disable
#!! to remove if this gets fixed
compdef -d git

#===history
if [ -z "$HISTFILE" ]; then
	HISTFILE="$HOME/.zsh_history"
fi
HISTSIZE=10000
SAVEHIST=10000

setopt hist_expire_dups_first
setopt hist_ignore_space
setopt SHARE_HISTORY #-# share history across sessions
setopt HIST_IGNORE_ALL_DUPS

#--arrow keys match on partial history with 'zsh-history-substring-search' plugin
if typeset -f history-substring-search-up > /dev/null; then
	bindkey '^[[A' history-substring-search-up
	bindkey '^[[B' history-substring-search-down
fi

#===keys
#-@ based on https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh
#--vi mode
#---enable
bindkey -v
#---indicate vim command mode by changing cursor
zle-keymap-select () {
	case "$KEYMAP" in
		vicmd)
			PS1="%F{2}>%{$reset_color%}$TJMPSBASE" #--gray PS marker
			echo -ne "\e]12;#00cc00\a" #--green cursor
			print -n -- '\e[1 q' #--blink cursor
		;;
		viins|main)
			PS1="$TJMPSBASE" #--normal PS
			print -n '\e]112\a' #--normal cursor color
			print -n '\e[0 q' #--normal cursor
		;;
	esac
	zle reset-prompt
}
zle -N zle-keymap-select
#--fix delete key (forward delete)
if [[ "${terminfo[kdch1]}" != "" ]]; then
	bindkey "${terminfo[kdch1]}" delete-char
else
	bindkey "^[[3~" delete-char
	bindkey "^[3;5~" delete-char
	bindkey "\e[3~" delete-char
fi
#--word movements
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word
bindkey "\033b" backward-word
bindkey "\033f" forward-word
#--emacs
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line
bindkey '^k' vi-kill-eol

#==custom
if [ -f "${TJMDOT}/_local/zsh" ]; then
	source "${TJMDOT}/_local/zsh"
fi
