echo 'Welcome, '`whoami`', to zsh'

#==bash stuff
source $HOME/.bash_profile

#==options
setopt AUTO_CD #-# automatically change directory

#===completions
autoload -U compinit; compinit #-# completions
autoload predict-on; predict-on #-# inline completions
unsetopt correctall #-# auto correction of commands
unsetopt LIST_BEEP #-# disable awful errors when autocompleting

#===history
if [ -z $HISTFILE ]; then
	HISTFILE=$HOME/.zsh_history
fi
HISTSIZE=10000
SAVEHIST=10000

setopt APPEND_HISTORY #-# enable history?
setopt hist_expire_dups_first
setopt hist_ignore_space
setopt INC_APPEND_HISTORY #-# append history incrementally
setopt SHARE_HISTORY #-# share history across sessions
setopt HIST_IGNORE_ALL_DUPS

#===keys
#-@ based on https://github.com/robbyrussell/oh-my-zsh/blob/master/lib/key-bindings.zsh
#--fix delete key (forward delete)
if [[ "${terminfo[kdch1]}" != "" ]]; then
	bindkey "${terminfo[kdch1]}" delete-char
else
	bindkey "^[[3~" delete-char
	bindkey "^[3;5~" delete-char
	bindkey "\e[3~" delete-char
fi
#--word movements
bindkey '^[[1;5D' backward-word
bindkey '^[[1;5C' forward-word

#==prompt
autoload -U colors && colors
PS1="[%n:%1d]>"
tputColors="$(tput colors 2> /dev/null || echo 2)"
if [ $tputColors -gt 2 ]; then
	if [ $tputColors -gt 8 ]; then
		tputFG="$(tput setab 42)$(tput setaf 0)"
	else
		tputFG="%{$bg[green]%}%{$fg[white]%}"
	fi
	tputReset="%{$reset_color%}"
	PS1="${tputFG}${PS1}${tputReset}"
fi
export PS1="$PS1 "
